import fs from 'node:fs';
const need=(v,m)=>{if(!v)throw new Error(m)};
const cfg=JSON.parse(fs.readFileSync('world-generator/configs/global-atlas.region.json','utf8'));
const manifest=JSON.parse(fs.readFileSync('regions/global-atlas/manifest.json','utf8'));
const runtime=fs.readFileSync('mallorca-mobile/adventure-0210/global-atlas-0260.js','utf8');
const index=fs.readFileSync('mallorca-mobile/adventure-0210/index.html','utf8');
const terrain=fs.readFileSync('regions/global-atlas/terrain.bin');
need(cfg.id==='global-atlas'&&cfg.version==='0.26.0','global config/version');
need(cfg.geography.bounds.west===-180&&cfg.geography.bounds.east===180&&cfg.geography.bounds.south===-90&&cfg.geography.bounds.north===90,'global bounds');
need(Math.abs(cfg.geography.scale.horizontalUnitsPerKm-.33)<1e-9,'global horizontal scale');
need(cfg.generation.terrain.grid.columns===690&&cfg.generation.terrain.grid.rows===345,'global macro grid');
need(cfg.performance.budgets.visibleTriangles>=474032,'global triangle budget');
need(manifest?.region?.id==='global-atlas','global manifest');
need(Math.abs(Number(manifest?.projection?.unitsPerKm)-.33)<1e-9,'manifest global scale');
need(terrain.subarray(0,8).toString()==='WAFTHGT1','global terrain magic');
need(terrain.readUInt16LE(12)===690&&terrain.readUInt16LE(14)===345,'global terrain dimensions');
need(runtime.includes('WORLD_WIDTH')&&runtime.includes('wrapLon')&&runtime.includes('state.wraps++'),'Pacific position wrap runtime missing');
need(runtime.includes('uOffsetX')&&runtime.includes('state.pacificCopies++'),'Pacific visual wrap missing');
need(runtime.includes("const B={west:-180,east:180,south:-90,north:90}"),'runtime global bounds');
need(runtime.includes('WAFT_GLOBAL_DETAIL_STREAM_0260')&&runtime.includes('rebuildEuropeDetail'),'streamed Europe detail missing');
need(runtime.includes("sampleFromTerrain(state.europeTerrain,x,z,'global-atlas-europe-detail')")&&runtime.includes('uDetailEnabled'),'detail surface replacement missing');
need(runtime.includes("const base='../../regions/global-atlas/',detailBase='../../regions/europe-atlas/'")&&runtime.includes("loadBuffer(detailBase+'terrain.bin')")&&runtime.includes("loadBuffer(detailBase+'landcover.bin')"),'global terrain + Europe detail sources missing');
need(runtime.includes('window.WAFTEuropeAtlas0252=window.WAFTGlobalAtlas0260'),'Europe compatibility alias missing');
need(index.includes("window.__WAFT_ADVENTURE_BUILD__='0.26.0'"),'Adventure 0.26.0 bootstrap missing');
need(index.includes('global-atlas-0260.js')&&index.includes('__WAFT_GLOBAL_ATLAS_0260_ACTIVE__'),'Global atlas bootstrap missing');
need(index.includes('WAFT_GLOBAL_POSITION_API_0260')&&index.includes('setRegionalPosition(x,z,y=null)'),'Global position API missing');
console.log(JSON.stringify({valid:true,version:'0.26.0',bounds:cfg.geography.bounds,grid:cfg.generation.terrain.grid,triangles:(690-1)*(345-1)*2,unitsPerKm:.33,pacificWrap:true,pacificVisualWrap:true,europeDetailStreaming:true,terrainBytes:terrain.length},null,2));
