import{shapeStick}from"./movement-math.js";
export class Input{constructor({canvas,moveZone,joystickBase,joystickKnob,runButton,actionButton}){this.canvas=canvas;this.moveZone=moveZone;this.joystickBase=joystickBase;this.joystickKnob=joystickKnob;this.runButton=runButton;this.actionButton=actionButton;this.keys=new Set;this.stick={x:0,y:0,magnitude:0};this.cameraDelta={x:0,y:0};this.actionQueued=false;this.saveQueued=false;this.runningTouch=false;this.movePointer=null;this.cameraPointer=null;this.moveOrigin={x:0,y:0};this.lastCameraPoint=null;this.abort=new AbortController;this.bind()}
bind(){const{signal}=this.abort;window.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.code==="KeyS"){e.preventDefault();this.saveQueued=true;return}this.keys.add(e.code);if(e.code==="KeyE"&&!e.repeat)this.actionQueued=true},{signal});window.addEventListener("keyup",e=>this.keys.delete(e.code),{signal});window.addEventListener("blur",()=>this.reset(),{signal});this.moveZone.addEventListener("pointerdown",e=>{e.preventDefault();this.movePointer=e.pointerId;this.moveOrigin={x:e.clientX,y:e.clientY};this.joystickBase.hidden=false;this.joystickBase.style.left=`${e.clientX}px`;this.joystickBase.style.top=`${e.clientY}px`;this.moveZone.setPointerCapture(e.pointerId);this.updateStick(e)},{signal});this.moveZone.addEventListener("pointermove",e=>{if(e.pointerId===this.movePointer)this.updateStick(e)},{signal});const releaseMove=e=>{if(e.pointerId!==this.movePointer)return;this.movePointer=null;this.stick={x:0,y:0,magnitude:0};this.joystickKnob.style.transform="translate(0px, 0px)";this.joystickBase.hidden=true};this.moveZone.addEventListener("pointerup",releaseMove,{signal});this.moveZone.addEventListener("pointercancel",releaseMove,{signal});this.canvas.addEventListener("pointerdown",e=>{if(e.pointerType==="touch"&&e.clientX<innerWidth*.43)return;this.cameraPointer=e.pointerId;this.lastCameraPoint={x:e.clientX,y:e.clientY};this.canvas.setPointerCapture(e.pointerId)},{signal});this.canvas.addEventListener("pointermove",e=>{if(e.pointerId!==this.cameraPointer||!this.lastCameraPoint)return;this.cameraDelta.x+=e.clientX-this.lastCameraPoint.x;this.cameraDelta.y+=e.clientY-this.lastCameraPoint.y;this.lastCameraPoint={x:e.clientX,y:e.clientY}},{signal});const releaseCamera=e=>{if(e.pointerId!==this.cameraPointer)return;this.cameraPointer=null;this.lastCameraPoint=null};this.canvas.addEventListener("pointerup",releaseCamera,{signal});this.canvas.addEventListener("pointercancel",releaseCamera,{signal});const setRun=active=>{this.runningTouch=active;this.runButton.classList.toggle("active",active)};this.runButton.addEventListener("pointerdown",e=>{e.preventDefault();this.runButton.setPointerCapture(e.pointerId);setRun(true)},{signal});this.runButton.addEventListener("pointerup",()=>setRun(false),{signal});this.runButton.addEventListener("pointercancel",()=>setRun(false),{signal});this.actionButton.addEventListener("pointerdown",e=>{e.preventDefault();this.actionQueued=true;this.actionButton.classList.add("active")},{signal});this.actionButton.addEventListener("pointerup",()=>this.actionButton.classList.remove("active"),{signal});this.actionButton.addEventListener("pointercancel",()=>this.actionButton.classList.remove("active"),{signal})}
updateStick(e){const radius=44;let dx=e.clientX-this.moveOrigin.x,dy=e.clientY-this.moveOrigin.y;const length=Math.hypot(dx,dy);if(length>radius){dx=dx/length*radius;dy=dy/length*radius}this.joystickKnob.style.transform=`translate(${dx}px, ${dy}px)`;this.stick=shapeStick(dx/radius,-dy/radius)}
movement(){const x=(this.keys.has("KeyD")||this.keys.has("ArrowRight")?1:0)-(this.keys.has("KeyA")||this.keys.has("ArrowLeft")?1:0),y=(this.keys.has("KeyW")||this.keys.has("ArrowUp")?1:0)-(this.keys.has("KeyS")||this.keys.has("ArrowDown")?1:0);if(x||y)return shapeStick(x,y);return this.stick}
running(){return this.runningTouch||this.keys.has("ShiftLeft")||this.keys.has("ShiftRight")}
consumeCamera(){const d={...this.cameraDelta};this.cameraDelta.x=0;this.cameraDelta.y=0;return d}
consumeAction(){const v=this.actionQueued;this.actionQueued=false;return v}
consumeSave(){const v=this.saveQueued;this.saveQueued=false;return v}
reset(){this.keys.clear();this.stick={x:0,y:0,magnitude:0};this.runningTouch=false;this.joystickBase.hidden=true}
dispose(){this.abort.abort()}}
