import{cameraRelativeDirection}from"./movement-math.js";
const B=window.BABYLON;
function angleDelta(from,to){return Math.atan2(Math.sin(to-from),Math.cos(to-from))}
export class Player{constructor(world,input){this.world=world;this.input=input;this.root=world.player.root;this.visual=world.player.visual;this.camera=world.camera;this.cameraYaw=0;this.cameraPitch=.34;this.cameraDistance=7.2;this.speed=0;this.walkSpeed=4.25;this.runSpeed=7.1;this.cycle=0;this.target=this.root.position.add(new B.Vector3(0,1.65,0));this.updateCamera(1,true)}
restore(save){if(!save?.player)return;const p=this.world.resolvePosition(save.player.x,save.player.z);this.root.position.set(p.x,this.world.terrainHeight(p.x,p.z),p.z);this.root.rotation.y=Number.isFinite(save.player.yaw)?save.player.yaw:this.root.rotation.y;if(Number.isFinite(save.cameraYaw))this.cameraYaw=save.cameraYaw;if(Number.isFinite(save.cameraPitch))this.cameraPitch=save.cameraPitch;this.updateCamera(1,true)}
update(dt){const delta=Math.min(dt,.05),camera=this.input.consumeCamera();this.cameraYaw-=camera.x*.0039;this.cameraPitch=B.Scalar.Clamp(this.cameraPitch+camera.y*.0028,.16,.61);const stick=this.input.movement(),wantedSpeed=stick.magnitude*(this.input.running()?this.runSpeed:this.walkSpeed),accel=wantedSpeed>this.speed?11:16;this.speed=B.Scalar.Lerp(this.speed,wantedSpeed,Math.min(1,delta*accel));if(stick.magnitude>.001){const direction=cameraRelativeDirection(stick.x,stick.y,this.cameraYaw),distance=this.speed*delta,resolved=this.world.resolvePosition(this.root.position.x+direction.x*distance,this.root.position.z+direction.z*distance);this.root.position.x=resolved.x;this.root.position.z=resolved.z;const heading=Math.atan2(direction.x,direction.z);this.root.rotation.y+=angleDelta(this.root.rotation.y,heading)*Math.min(1,delta*13)}const ground=this.world.terrainHeight(this.root.position.x,this.root.position.z);this.root.position.y=B.Scalar.Lerp(this.root.position.y,ground,Math.min(1,delta*20));this.animate(delta,stick.magnitude);this.updateCamera(delta,false)}
animate(delta,magnitude){this.cycle+=delta*(2.8+this.speed*1.05);const moving=Math.min(1,magnitude*1.4),swing=Math.sin(this.cycle)*moving;this.world.player.arms[0].rotation.x=swing*.7;this.world.player.arms[1].rotation.x=-swing*.7;this.world.player.legs[0].rotation.x=-swing*.48;this.world.player.legs[1].rotation.x=swing*.48;this.visual.position.y=Math.abs(Math.sin(this.cycle*2))*moving*.035;this.visual.rotation.x=-.09+Math.min(.08,this.speed*.008);if(moving<.05){this.visual.position.y=Math.sin(this.cycle*.35)*.012;this.world.player.arms[0].rotation.x*=.88;this.world.player.arms[1].rotation.x*=.88;this.world.player.legs[0].rotation.x*=.88;this.world.player.legs[1].rotation.x*=.88}}
updateCamera(delta,immediate){const rawTarget=this.root.position.add(new B.Vector3(0,1.72,0)),blend=immediate?1:Math.min(1,delta*14);this.target=B.Vector3.Lerp(this.target,rawTarget,blend);const horizontal=Math.cos(this.cameraPitch)*this.cameraDistance,desired=new B.Vector3(this.target.x+Math.sin(this.cameraYaw)*horizontal,this.target.y+Math.sin(this.cameraPitch)*this.cameraDistance+.5,this.target.z+Math.cos(this.cameraYaw)*horizontal);desired.y=Math.max(desired.y,this.world.terrainHeight(desired.x,desired.z)+.85);this.camera.position.copyFrom(immediate?desired:B.Vector3.Lerp(this.camera.position,desired,Math.min(1,delta*10)));this.camera.setTarget(this.target)}
snapshot(){return{player:{x:this.root.position.x,z:this.root.position.z,yaw:this.root.rotation.y},cameraYaw:this.cameraYaw,cameraPitch:this.cameraPitch}}}
